<?php
/**
 * CatalogDataProductExtensionInterface
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Magento2Client
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Magento Enterprise
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Magento2Client\Model;

use \ArrayAccess;

/**
 * CatalogDataProductExtensionInterface Class Doc Comment
 *
 * @category    Class
 * @description ExtensionInterface class for @see \\Magento\\Catalog\\Api\\Data\\ProductInterface
 * @package     Swagger\Magento2Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CatalogDataProductExtensionInterface implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'catalog-data-product-extension-interface';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'downloadable_product_links' => '\Swagger\Magento2Client\Model\DownloadableDataLinkInterface[]',
        'downloadable_product_samples' => '\Swagger\Magento2Client\Model\DownloadableDataSampleInterface[]',
        'stock_item' => '\Swagger\Magento2Client\Model\CatalogInventoryDataStockItemInterface',
        'giftcard_amounts' => '\Swagger\Magento2Client\Model\GiftCardDataGiftcardAmountInterface[]',
        'configurable_product_options' => '\Swagger\Magento2Client\Model\ConfigurableProductDataOptionInterface[]',
        'configurable_product_links' => 'int[]',
        'bundle_product_options' => '\Swagger\Magento2Client\Model\BundleDataOptionInterface[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerFormats = [
        'downloadable_product_links' => null,
        'downloadable_product_samples' => null,
        'stock_item' => null,
        'giftcard_amounts' => null,
        'configurable_product_options' => null,
        'configurable_product_links' => null,
        'bundle_product_options' => null
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'downloadable_product_links' => 'downloadableProductLinks',
        'downloadable_product_samples' => 'downloadableProductSamples',
        'stock_item' => 'stockItem',
        'giftcard_amounts' => 'giftcardAmounts',
        'configurable_product_options' => 'configurableProductOptions',
        'configurable_product_links' => 'configurableProductLinks',
        'bundle_product_options' => 'bundleProductOptions'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'downloadable_product_links' => 'setDownloadableProductLinks',
        'downloadable_product_samples' => 'setDownloadableProductSamples',
        'stock_item' => 'setStockItem',
        'giftcard_amounts' => 'setGiftcardAmounts',
        'configurable_product_options' => 'setConfigurableProductOptions',
        'configurable_product_links' => 'setConfigurableProductLinks',
        'bundle_product_options' => 'setBundleProductOptions'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'downloadable_product_links' => 'getDownloadableProductLinks',
        'downloadable_product_samples' => 'getDownloadableProductSamples',
        'stock_item' => 'getStockItem',
        'giftcard_amounts' => 'getGiftcardAmounts',
        'configurable_product_options' => 'getConfigurableProductOptions',
        'configurable_product_links' => 'getConfigurableProductLinks',
        'bundle_product_options' => 'getBundleProductOptions'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['downloadable_product_links'] = isset($data['downloadable_product_links']) ? $data['downloadable_product_links'] : null;
        $this->container['downloadable_product_samples'] = isset($data['downloadable_product_samples']) ? $data['downloadable_product_samples'] : null;
        $this->container['stock_item'] = isset($data['stock_item']) ? $data['stock_item'] : null;
        $this->container['giftcard_amounts'] = isset($data['giftcard_amounts']) ? $data['giftcard_amounts'] : null;
        $this->container['configurable_product_options'] = isset($data['configurable_product_options']) ? $data['configurable_product_options'] : null;
        $this->container['configurable_product_links'] = isset($data['configurable_product_links']) ? $data['configurable_product_links'] : null;
        $this->container['bundle_product_options'] = isset($data['bundle_product_options']) ? $data['bundle_product_options'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
     * Gets downloadable_product_links
     * @return \Swagger\Magento2Client\Model\DownloadableDataLinkInterface[]
     */
    public function getDownloadableProductLinks()
    {
        return $this->container['downloadable_product_links'];
    }

    /**
     * Sets downloadable_product_links
     * @param \Swagger\Magento2Client\Model\DownloadableDataLinkInterface[] $downloadable_product_links
     * @return $this
     */
    public function setDownloadableProductLinks($downloadable_product_links)
    {
        $this->container['downloadable_product_links'] = $downloadable_product_links;

        return $this;
    }

    /**
     * Gets downloadable_product_samples
     * @return \Swagger\Magento2Client\Model\DownloadableDataSampleInterface[]
     */
    public function getDownloadableProductSamples()
    {
        return $this->container['downloadable_product_samples'];
    }

    /**
     * Sets downloadable_product_samples
     * @param \Swagger\Magento2Client\Model\DownloadableDataSampleInterface[] $downloadable_product_samples
     * @return $this
     */
    public function setDownloadableProductSamples($downloadable_product_samples)
    {
        $this->container['downloadable_product_samples'] = $downloadable_product_samples;

        return $this;
    }

    /**
     * Gets stock_item
     * @return \Swagger\Magento2Client\Model\CatalogInventoryDataStockItemInterface
     */
    public function getStockItem()
    {
        return $this->container['stock_item'];
    }

    /**
     * Sets stock_item
     * @param \Swagger\Magento2Client\Model\CatalogInventoryDataStockItemInterface $stock_item
     * @return $this
     */
    public function setStockItem($stock_item)
    {
        $this->container['stock_item'] = $stock_item;

        return $this;
    }

    /**
     * Gets giftcard_amounts
     * @return \Swagger\Magento2Client\Model\GiftCardDataGiftcardAmountInterface[]
     */
    public function getGiftcardAmounts()
    {
        return $this->container['giftcard_amounts'];
    }

    /**
     * Sets giftcard_amounts
     * @param \Swagger\Magento2Client\Model\GiftCardDataGiftcardAmountInterface[] $giftcard_amounts
     * @return $this
     */
    public function setGiftcardAmounts($giftcard_amounts)
    {
        $this->container['giftcard_amounts'] = $giftcard_amounts;

        return $this;
    }

    /**
     * Gets configurable_product_options
     * @return \Swagger\Magento2Client\Model\ConfigurableProductDataOptionInterface[]
     */
    public function getConfigurableProductOptions()
    {
        return $this->container['configurable_product_options'];
    }

    /**
     * Sets configurable_product_options
     * @param \Swagger\Magento2Client\Model\ConfigurableProductDataOptionInterface[] $configurable_product_options
     * @return $this
     */
    public function setConfigurableProductOptions($configurable_product_options)
    {
        $this->container['configurable_product_options'] = $configurable_product_options;

        return $this;
    }

    /**
     * Gets configurable_product_links
     * @return int[]
     */
    public function getConfigurableProductLinks()
    {
        return $this->container['configurable_product_links'];
    }

    /**
     * Sets configurable_product_links
     * @param int[] $configurable_product_links
     * @return $this
     */
    public function setConfigurableProductLinks($configurable_product_links)
    {
        $this->container['configurable_product_links'] = $configurable_product_links;

        return $this;
    }

    /**
     * Gets bundle_product_options
     * @return \Swagger\Magento2Client\Model\BundleDataOptionInterface[]
     */
    public function getBundleProductOptions()
    {
        return $this->container['bundle_product_options'];
    }

    /**
     * Sets bundle_product_options
     * @param \Swagger\Magento2Client\Model\BundleDataOptionInterface[] $bundle_product_options
     * @return $this
     */
    public function setBundleProductOptions($bundle_product_options)
    {
        $this->container['bundle_product_options'] = $bundle_product_options;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Swagger\Magento2Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Swagger\Magento2Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}


