<?php
/**
 * QuoteDataTotalsExtensionInterface
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Magento2Client
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Magento Enterprise
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Magento2Client\Model;

use \ArrayAccess;

/**
 * QuoteDataTotalsExtensionInterface Class Doc Comment
 *
 * @category    Class
 * @description ExtensionInterface class for @see \\Magento\\Quote\\Api\\Data\\TotalsInterface
 * @package     Swagger\Magento2Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class QuoteDataTotalsExtensionInterface implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'quote-data-totals-extension-interface';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'reward_points_balance' => 'float',
        'reward_currency_amount' => 'float',
        'base_reward_currency_amount' => 'float'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerFormats = [
        'reward_points_balance' => null,
        'reward_currency_amount' => null,
        'base_reward_currency_amount' => null
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'reward_points_balance' => 'rewardPointsBalance',
        'reward_currency_amount' => 'rewardCurrencyAmount',
        'base_reward_currency_amount' => 'baseRewardCurrencyAmount'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'reward_points_balance' => 'setRewardPointsBalance',
        'reward_currency_amount' => 'setRewardCurrencyAmount',
        'base_reward_currency_amount' => 'setBaseRewardCurrencyAmount'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'reward_points_balance' => 'getRewardPointsBalance',
        'reward_currency_amount' => 'getRewardCurrencyAmount',
        'base_reward_currency_amount' => 'getBaseRewardCurrencyAmount'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['reward_points_balance'] = isset($data['reward_points_balance']) ? $data['reward_points_balance'] : null;
        $this->container['reward_currency_amount'] = isset($data['reward_currency_amount']) ? $data['reward_currency_amount'] : null;
        $this->container['base_reward_currency_amount'] = isset($data['base_reward_currency_amount']) ? $data['base_reward_currency_amount'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
     * Gets reward_points_balance
     * @return float
     */
    public function getRewardPointsBalance()
    {
        return $this->container['reward_points_balance'];
    }

    /**
     * Sets reward_points_balance
     * @param float $reward_points_balance
     * @return $this
     */
    public function setRewardPointsBalance($reward_points_balance)
    {
        $this->container['reward_points_balance'] = $reward_points_balance;

        return $this;
    }

    /**
     * Gets reward_currency_amount
     * @return float
     */
    public function getRewardCurrencyAmount()
    {
        return $this->container['reward_currency_amount'];
    }

    /**
     * Sets reward_currency_amount
     * @param float $reward_currency_amount
     * @return $this
     */
    public function setRewardCurrencyAmount($reward_currency_amount)
    {
        $this->container['reward_currency_amount'] = $reward_currency_amount;

        return $this;
    }

    /**
     * Gets base_reward_currency_amount
     * @return float
     */
    public function getBaseRewardCurrencyAmount()
    {
        return $this->container['base_reward_currency_amount'];
    }

    /**
     * Sets base_reward_currency_amount
     * @param float $base_reward_currency_amount
     * @return $this
     */
    public function setBaseRewardCurrencyAmount($base_reward_currency_amount)
    {
        $this->container['base_reward_currency_amount'] = $base_reward_currency_amount;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Swagger\Magento2Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Swagger\Magento2Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}


