<?php
/**
 * SalesDataOrderExtensionInterface
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Magento2Client
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Magento Enterprise
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Magento2Client\Model;

use \ArrayAccess;

/**
 * SalesDataOrderExtensionInterface Class Doc Comment
 *
 * @category    Class
 * @description ExtensionInterface class for @see \\Magento\\Sales\\Api\\Data\\OrderInterface
 * @package     Swagger\Magento2Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SalesDataOrderExtensionInterface implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'sales-data-order-extension-interface';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'shipping_assignments' => '\Swagger\Magento2Client\Model\SalesDataShippingAssignmentInterface[]',
        'applied_taxes' => '\Swagger\Magento2Client\Model\TaxDataOrderTaxDetailsAppliedTaxInterface[]',
        'item_applied_taxes' => '\Swagger\Magento2Client\Model\TaxDataOrderTaxDetailsItemInterface[]',
        'converting_from_quote' => 'bool',
        'gift_message' => '\Swagger\Magento2Client\Model\GiftMessageDataMessageInterface',
        'gw_id' => 'string',
        'gw_allow_gift_receipt' => 'string',
        'gw_add_card' => 'string',
        'gw_price' => 'string',
        'gw_base_price' => 'string',
        'gw_items_price' => 'string',
        'gw_items_base_price' => 'string',
        'gw_card_price' => 'string',
        'gw_card_base_price' => 'string',
        'gw_base_tax_amount' => 'string',
        'gw_tax_amount' => 'string',
        'gw_items_base_tax_amount' => 'string',
        'gw_items_tax_amount' => 'string',
        'gw_card_base_tax_amount' => 'string',
        'gw_card_tax_amount' => 'string',
        'gw_price_incl_tax' => 'string',
        'gw_base_price_incl_tax' => 'string',
        'gw_card_price_incl_tax' => 'string',
        'gw_card_base_price_incl_tax' => 'string',
        'gw_items_price_incl_tax' => 'string',
        'gw_items_base_price_incl_tax' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerFormats = [
        'shipping_assignments' => null,
        'applied_taxes' => null,
        'item_applied_taxes' => null,
        'converting_from_quote' => null,
        'gift_message' => null,
        'gw_id' => null,
        'gw_allow_gift_receipt' => null,
        'gw_add_card' => null,
        'gw_price' => null,
        'gw_base_price' => null,
        'gw_items_price' => null,
        'gw_items_base_price' => null,
        'gw_card_price' => null,
        'gw_card_base_price' => null,
        'gw_base_tax_amount' => null,
        'gw_tax_amount' => null,
        'gw_items_base_tax_amount' => null,
        'gw_items_tax_amount' => null,
        'gw_card_base_tax_amount' => null,
        'gw_card_tax_amount' => null,
        'gw_price_incl_tax' => null,
        'gw_base_price_incl_tax' => null,
        'gw_card_price_incl_tax' => null,
        'gw_card_base_price_incl_tax' => null,
        'gw_items_price_incl_tax' => null,
        'gw_items_base_price_incl_tax' => null
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'shipping_assignments' => 'shippingAssignments',
        'applied_taxes' => 'appliedTaxes',
        'item_applied_taxes' => 'itemAppliedTaxes',
        'converting_from_quote' => 'convertingFromQuote',
        'gift_message' => 'giftMessage',
        'gw_id' => 'gwId',
        'gw_allow_gift_receipt' => 'gwAllowGiftReceipt',
        'gw_add_card' => 'gwAddCard',
        'gw_price' => 'gwPrice',
        'gw_base_price' => 'gwBasePrice',
        'gw_items_price' => 'gwItemsPrice',
        'gw_items_base_price' => 'gwItemsBasePrice',
        'gw_card_price' => 'gwCardPrice',
        'gw_card_base_price' => 'gwCardBasePrice',
        'gw_base_tax_amount' => 'gwBaseTaxAmount',
        'gw_tax_amount' => 'gwTaxAmount',
        'gw_items_base_tax_amount' => 'gwItemsBaseTaxAmount',
        'gw_items_tax_amount' => 'gwItemsTaxAmount',
        'gw_card_base_tax_amount' => 'gwCardBaseTaxAmount',
        'gw_card_tax_amount' => 'gwCardTaxAmount',
        'gw_price_incl_tax' => 'gwPriceInclTax',
        'gw_base_price_incl_tax' => 'gwBasePriceInclTax',
        'gw_card_price_incl_tax' => 'gwCardPriceInclTax',
        'gw_card_base_price_incl_tax' => 'gwCardBasePriceInclTax',
        'gw_items_price_incl_tax' => 'gwItemsPriceInclTax',
        'gw_items_base_price_incl_tax' => 'gwItemsBasePriceInclTax'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'shipping_assignments' => 'setShippingAssignments',
        'applied_taxes' => 'setAppliedTaxes',
        'item_applied_taxes' => 'setItemAppliedTaxes',
        'converting_from_quote' => 'setConvertingFromQuote',
        'gift_message' => 'setGiftMessage',
        'gw_id' => 'setGwId',
        'gw_allow_gift_receipt' => 'setGwAllowGiftReceipt',
        'gw_add_card' => 'setGwAddCard',
        'gw_price' => 'setGwPrice',
        'gw_base_price' => 'setGwBasePrice',
        'gw_items_price' => 'setGwItemsPrice',
        'gw_items_base_price' => 'setGwItemsBasePrice',
        'gw_card_price' => 'setGwCardPrice',
        'gw_card_base_price' => 'setGwCardBasePrice',
        'gw_base_tax_amount' => 'setGwBaseTaxAmount',
        'gw_tax_amount' => 'setGwTaxAmount',
        'gw_items_base_tax_amount' => 'setGwItemsBaseTaxAmount',
        'gw_items_tax_amount' => 'setGwItemsTaxAmount',
        'gw_card_base_tax_amount' => 'setGwCardBaseTaxAmount',
        'gw_card_tax_amount' => 'setGwCardTaxAmount',
        'gw_price_incl_tax' => 'setGwPriceInclTax',
        'gw_base_price_incl_tax' => 'setGwBasePriceInclTax',
        'gw_card_price_incl_tax' => 'setGwCardPriceInclTax',
        'gw_card_base_price_incl_tax' => 'setGwCardBasePriceInclTax',
        'gw_items_price_incl_tax' => 'setGwItemsPriceInclTax',
        'gw_items_base_price_incl_tax' => 'setGwItemsBasePriceInclTax'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'shipping_assignments' => 'getShippingAssignments',
        'applied_taxes' => 'getAppliedTaxes',
        'item_applied_taxes' => 'getItemAppliedTaxes',
        'converting_from_quote' => 'getConvertingFromQuote',
        'gift_message' => 'getGiftMessage',
        'gw_id' => 'getGwId',
        'gw_allow_gift_receipt' => 'getGwAllowGiftReceipt',
        'gw_add_card' => 'getGwAddCard',
        'gw_price' => 'getGwPrice',
        'gw_base_price' => 'getGwBasePrice',
        'gw_items_price' => 'getGwItemsPrice',
        'gw_items_base_price' => 'getGwItemsBasePrice',
        'gw_card_price' => 'getGwCardPrice',
        'gw_card_base_price' => 'getGwCardBasePrice',
        'gw_base_tax_amount' => 'getGwBaseTaxAmount',
        'gw_tax_amount' => 'getGwTaxAmount',
        'gw_items_base_tax_amount' => 'getGwItemsBaseTaxAmount',
        'gw_items_tax_amount' => 'getGwItemsTaxAmount',
        'gw_card_base_tax_amount' => 'getGwCardBaseTaxAmount',
        'gw_card_tax_amount' => 'getGwCardTaxAmount',
        'gw_price_incl_tax' => 'getGwPriceInclTax',
        'gw_base_price_incl_tax' => 'getGwBasePriceInclTax',
        'gw_card_price_incl_tax' => 'getGwCardPriceInclTax',
        'gw_card_base_price_incl_tax' => 'getGwCardBasePriceInclTax',
        'gw_items_price_incl_tax' => 'getGwItemsPriceInclTax',
        'gw_items_base_price_incl_tax' => 'getGwItemsBasePriceInclTax'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['shipping_assignments'] = isset($data['shipping_assignments']) ? $data['shipping_assignments'] : null;
        $this->container['applied_taxes'] = isset($data['applied_taxes']) ? $data['applied_taxes'] : null;
        $this->container['item_applied_taxes'] = isset($data['item_applied_taxes']) ? $data['item_applied_taxes'] : null;
        $this->container['converting_from_quote'] = isset($data['converting_from_quote']) ? $data['converting_from_quote'] : null;
        $this->container['gift_message'] = isset($data['gift_message']) ? $data['gift_message'] : null;
        $this->container['gw_id'] = isset($data['gw_id']) ? $data['gw_id'] : null;
        $this->container['gw_allow_gift_receipt'] = isset($data['gw_allow_gift_receipt']) ? $data['gw_allow_gift_receipt'] : null;
        $this->container['gw_add_card'] = isset($data['gw_add_card']) ? $data['gw_add_card'] : null;
        $this->container['gw_price'] = isset($data['gw_price']) ? $data['gw_price'] : null;
        $this->container['gw_base_price'] = isset($data['gw_base_price']) ? $data['gw_base_price'] : null;
        $this->container['gw_items_price'] = isset($data['gw_items_price']) ? $data['gw_items_price'] : null;
        $this->container['gw_items_base_price'] = isset($data['gw_items_base_price']) ? $data['gw_items_base_price'] : null;
        $this->container['gw_card_price'] = isset($data['gw_card_price']) ? $data['gw_card_price'] : null;
        $this->container['gw_card_base_price'] = isset($data['gw_card_base_price']) ? $data['gw_card_base_price'] : null;
        $this->container['gw_base_tax_amount'] = isset($data['gw_base_tax_amount']) ? $data['gw_base_tax_amount'] : null;
        $this->container['gw_tax_amount'] = isset($data['gw_tax_amount']) ? $data['gw_tax_amount'] : null;
        $this->container['gw_items_base_tax_amount'] = isset($data['gw_items_base_tax_amount']) ? $data['gw_items_base_tax_amount'] : null;
        $this->container['gw_items_tax_amount'] = isset($data['gw_items_tax_amount']) ? $data['gw_items_tax_amount'] : null;
        $this->container['gw_card_base_tax_amount'] = isset($data['gw_card_base_tax_amount']) ? $data['gw_card_base_tax_amount'] : null;
        $this->container['gw_card_tax_amount'] = isset($data['gw_card_tax_amount']) ? $data['gw_card_tax_amount'] : null;
        $this->container['gw_price_incl_tax'] = isset($data['gw_price_incl_tax']) ? $data['gw_price_incl_tax'] : null;
        $this->container['gw_base_price_incl_tax'] = isset($data['gw_base_price_incl_tax']) ? $data['gw_base_price_incl_tax'] : null;
        $this->container['gw_card_price_incl_tax'] = isset($data['gw_card_price_incl_tax']) ? $data['gw_card_price_incl_tax'] : null;
        $this->container['gw_card_base_price_incl_tax'] = isset($data['gw_card_base_price_incl_tax']) ? $data['gw_card_base_price_incl_tax'] : null;
        $this->container['gw_items_price_incl_tax'] = isset($data['gw_items_price_incl_tax']) ? $data['gw_items_price_incl_tax'] : null;
        $this->container['gw_items_base_price_incl_tax'] = isset($data['gw_items_base_price_incl_tax']) ? $data['gw_items_base_price_incl_tax'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
     * Gets shipping_assignments
     * @return \Swagger\Magento2Client\Model\SalesDataShippingAssignmentInterface[]
     */
    public function getShippingAssignments()
    {
        return $this->container['shipping_assignments'];
    }

    /**
     * Sets shipping_assignments
     * @param \Swagger\Magento2Client\Model\SalesDataShippingAssignmentInterface[] $shipping_assignments
     * @return $this
     */
    public function setShippingAssignments($shipping_assignments)
    {
        $this->container['shipping_assignments'] = $shipping_assignments;

        return $this;
    }

    /**
     * Gets applied_taxes
     * @return \Swagger\Magento2Client\Model\TaxDataOrderTaxDetailsAppliedTaxInterface[]
     */
    public function getAppliedTaxes()
    {
        return $this->container['applied_taxes'];
    }

    /**
     * Sets applied_taxes
     * @param \Swagger\Magento2Client\Model\TaxDataOrderTaxDetailsAppliedTaxInterface[] $applied_taxes
     * @return $this
     */
    public function setAppliedTaxes($applied_taxes)
    {
        $this->container['applied_taxes'] = $applied_taxes;

        return $this;
    }

    /**
     * Gets item_applied_taxes
     * @return \Swagger\Magento2Client\Model\TaxDataOrderTaxDetailsItemInterface[]
     */
    public function getItemAppliedTaxes()
    {
        return $this->container['item_applied_taxes'];
    }

    /**
     * Sets item_applied_taxes
     * @param \Swagger\Magento2Client\Model\TaxDataOrderTaxDetailsItemInterface[] $item_applied_taxes
     * @return $this
     */
    public function setItemAppliedTaxes($item_applied_taxes)
    {
        $this->container['item_applied_taxes'] = $item_applied_taxes;

        return $this;
    }

    /**
     * Gets converting_from_quote
     * @return bool
     */
    public function getConvertingFromQuote()
    {
        return $this->container['converting_from_quote'];
    }

    /**
     * Sets converting_from_quote
     * @param bool $converting_from_quote
     * @return $this
     */
    public function setConvertingFromQuote($converting_from_quote)
    {
        $this->container['converting_from_quote'] = $converting_from_quote;

        return $this;
    }

    /**
     * Gets gift_message
     * @return \Swagger\Magento2Client\Model\GiftMessageDataMessageInterface
     */
    public function getGiftMessage()
    {
        return $this->container['gift_message'];
    }

    /**
     * Sets gift_message
     * @param \Swagger\Magento2Client\Model\GiftMessageDataMessageInterface $gift_message
     * @return $this
     */
    public function setGiftMessage($gift_message)
    {
        $this->container['gift_message'] = $gift_message;

        return $this;
    }

    /**
     * Gets gw_id
     * @return string
     */
    public function getGwId()
    {
        return $this->container['gw_id'];
    }

    /**
     * Sets gw_id
     * @param string $gw_id
     * @return $this
     */
    public function setGwId($gw_id)
    {
        $this->container['gw_id'] = $gw_id;

        return $this;
    }

    /**
     * Gets gw_allow_gift_receipt
     * @return string
     */
    public function getGwAllowGiftReceipt()
    {
        return $this->container['gw_allow_gift_receipt'];
    }

    /**
     * Sets gw_allow_gift_receipt
     * @param string $gw_allow_gift_receipt
     * @return $this
     */
    public function setGwAllowGiftReceipt($gw_allow_gift_receipt)
    {
        $this->container['gw_allow_gift_receipt'] = $gw_allow_gift_receipt;

        return $this;
    }

    /**
     * Gets gw_add_card
     * @return string
     */
    public function getGwAddCard()
    {
        return $this->container['gw_add_card'];
    }

    /**
     * Sets gw_add_card
     * @param string $gw_add_card
     * @return $this
     */
    public function setGwAddCard($gw_add_card)
    {
        $this->container['gw_add_card'] = $gw_add_card;

        return $this;
    }

    /**
     * Gets gw_price
     * @return string
     */
    public function getGwPrice()
    {
        return $this->container['gw_price'];
    }

    /**
     * Sets gw_price
     * @param string $gw_price
     * @return $this
     */
    public function setGwPrice($gw_price)
    {
        $this->container['gw_price'] = $gw_price;

        return $this;
    }

    /**
     * Gets gw_base_price
     * @return string
     */
    public function getGwBasePrice()
    {
        return $this->container['gw_base_price'];
    }

    /**
     * Sets gw_base_price
     * @param string $gw_base_price
     * @return $this
     */
    public function setGwBasePrice($gw_base_price)
    {
        $this->container['gw_base_price'] = $gw_base_price;

        return $this;
    }

    /**
     * Gets gw_items_price
     * @return string
     */
    public function getGwItemsPrice()
    {
        return $this->container['gw_items_price'];
    }

    /**
     * Sets gw_items_price
     * @param string $gw_items_price
     * @return $this
     */
    public function setGwItemsPrice($gw_items_price)
    {
        $this->container['gw_items_price'] = $gw_items_price;

        return $this;
    }

    /**
     * Gets gw_items_base_price
     * @return string
     */
    public function getGwItemsBasePrice()
    {
        return $this->container['gw_items_base_price'];
    }

    /**
     * Sets gw_items_base_price
     * @param string $gw_items_base_price
     * @return $this
     */
    public function setGwItemsBasePrice($gw_items_base_price)
    {
        $this->container['gw_items_base_price'] = $gw_items_base_price;

        return $this;
    }

    /**
     * Gets gw_card_price
     * @return string
     */
    public function getGwCardPrice()
    {
        return $this->container['gw_card_price'];
    }

    /**
     * Sets gw_card_price
     * @param string $gw_card_price
     * @return $this
     */
    public function setGwCardPrice($gw_card_price)
    {
        $this->container['gw_card_price'] = $gw_card_price;

        return $this;
    }

    /**
     * Gets gw_card_base_price
     * @return string
     */
    public function getGwCardBasePrice()
    {
        return $this->container['gw_card_base_price'];
    }

    /**
     * Sets gw_card_base_price
     * @param string $gw_card_base_price
     * @return $this
     */
    public function setGwCardBasePrice($gw_card_base_price)
    {
        $this->container['gw_card_base_price'] = $gw_card_base_price;

        return $this;
    }

    /**
     * Gets gw_base_tax_amount
     * @return string
     */
    public function getGwBaseTaxAmount()
    {
        return $this->container['gw_base_tax_amount'];
    }

    /**
     * Sets gw_base_tax_amount
     * @param string $gw_base_tax_amount
     * @return $this
     */
    public function setGwBaseTaxAmount($gw_base_tax_amount)
    {
        $this->container['gw_base_tax_amount'] = $gw_base_tax_amount;

        return $this;
    }

    /**
     * Gets gw_tax_amount
     * @return string
     */
    public function getGwTaxAmount()
    {
        return $this->container['gw_tax_amount'];
    }

    /**
     * Sets gw_tax_amount
     * @param string $gw_tax_amount
     * @return $this
     */
    public function setGwTaxAmount($gw_tax_amount)
    {
        $this->container['gw_tax_amount'] = $gw_tax_amount;

        return $this;
    }

    /**
     * Gets gw_items_base_tax_amount
     * @return string
     */
    public function getGwItemsBaseTaxAmount()
    {
        return $this->container['gw_items_base_tax_amount'];
    }

    /**
     * Sets gw_items_base_tax_amount
     * @param string $gw_items_base_tax_amount
     * @return $this
     */
    public function setGwItemsBaseTaxAmount($gw_items_base_tax_amount)
    {
        $this->container['gw_items_base_tax_amount'] = $gw_items_base_tax_amount;

        return $this;
    }

    /**
     * Gets gw_items_tax_amount
     * @return string
     */
    public function getGwItemsTaxAmount()
    {
        return $this->container['gw_items_tax_amount'];
    }

    /**
     * Sets gw_items_tax_amount
     * @param string $gw_items_tax_amount
     * @return $this
     */
    public function setGwItemsTaxAmount($gw_items_tax_amount)
    {
        $this->container['gw_items_tax_amount'] = $gw_items_tax_amount;

        return $this;
    }

    /**
     * Gets gw_card_base_tax_amount
     * @return string
     */
    public function getGwCardBaseTaxAmount()
    {
        return $this->container['gw_card_base_tax_amount'];
    }

    /**
     * Sets gw_card_base_tax_amount
     * @param string $gw_card_base_tax_amount
     * @return $this
     */
    public function setGwCardBaseTaxAmount($gw_card_base_tax_amount)
    {
        $this->container['gw_card_base_tax_amount'] = $gw_card_base_tax_amount;

        return $this;
    }

    /**
     * Gets gw_card_tax_amount
     * @return string
     */
    public function getGwCardTaxAmount()
    {
        return $this->container['gw_card_tax_amount'];
    }

    /**
     * Sets gw_card_tax_amount
     * @param string $gw_card_tax_amount
     * @return $this
     */
    public function setGwCardTaxAmount($gw_card_tax_amount)
    {
        $this->container['gw_card_tax_amount'] = $gw_card_tax_amount;

        return $this;
    }

    /**
     * Gets gw_price_incl_tax
     * @return string
     */
    public function getGwPriceInclTax()
    {
        return $this->container['gw_price_incl_tax'];
    }

    /**
     * Sets gw_price_incl_tax
     * @param string $gw_price_incl_tax
     * @return $this
     */
    public function setGwPriceInclTax($gw_price_incl_tax)
    {
        $this->container['gw_price_incl_tax'] = $gw_price_incl_tax;

        return $this;
    }

    /**
     * Gets gw_base_price_incl_tax
     * @return string
     */
    public function getGwBasePriceInclTax()
    {
        return $this->container['gw_base_price_incl_tax'];
    }

    /**
     * Sets gw_base_price_incl_tax
     * @param string $gw_base_price_incl_tax
     * @return $this
     */
    public function setGwBasePriceInclTax($gw_base_price_incl_tax)
    {
        $this->container['gw_base_price_incl_tax'] = $gw_base_price_incl_tax;

        return $this;
    }

    /**
     * Gets gw_card_price_incl_tax
     * @return string
     */
    public function getGwCardPriceInclTax()
    {
        return $this->container['gw_card_price_incl_tax'];
    }

    /**
     * Sets gw_card_price_incl_tax
     * @param string $gw_card_price_incl_tax
     * @return $this
     */
    public function setGwCardPriceInclTax($gw_card_price_incl_tax)
    {
        $this->container['gw_card_price_incl_tax'] = $gw_card_price_incl_tax;

        return $this;
    }

    /**
     * Gets gw_card_base_price_incl_tax
     * @return string
     */
    public function getGwCardBasePriceInclTax()
    {
        return $this->container['gw_card_base_price_incl_tax'];
    }

    /**
     * Sets gw_card_base_price_incl_tax
     * @param string $gw_card_base_price_incl_tax
     * @return $this
     */
    public function setGwCardBasePriceInclTax($gw_card_base_price_incl_tax)
    {
        $this->container['gw_card_base_price_incl_tax'] = $gw_card_base_price_incl_tax;

        return $this;
    }

    /**
     * Gets gw_items_price_incl_tax
     * @return string
     */
    public function getGwItemsPriceInclTax()
    {
        return $this->container['gw_items_price_incl_tax'];
    }

    /**
     * Sets gw_items_price_incl_tax
     * @param string $gw_items_price_incl_tax
     * @return $this
     */
    public function setGwItemsPriceInclTax($gw_items_price_incl_tax)
    {
        $this->container['gw_items_price_incl_tax'] = $gw_items_price_incl_tax;

        return $this;
    }

    /**
     * Gets gw_items_base_price_incl_tax
     * @return string
     */
    public function getGwItemsBasePriceInclTax()
    {
        return $this->container['gw_items_base_price_incl_tax'];
    }

    /**
     * Sets gw_items_base_price_incl_tax
     * @param string $gw_items_base_price_incl_tax
     * @return $this
     */
    public function setGwItemsBasePriceInclTax($gw_items_base_price_incl_tax)
    {
        $this->container['gw_items_base_price_incl_tax'] = $gw_items_base_price_incl_tax;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Swagger\Magento2Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Swagger\Magento2Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}


