<?php
/**
 * EavDataAttributeGroupInterfaceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Magento2Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Magento Enterprise
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Magento2Client;

/**
 * EavDataAttributeGroupInterfaceTest Class Doc Comment
 *
 * @category    Class */
// * @description 
/**
 * @package     Swagger\Magento2Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EavDataAttributeGroupInterfaceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "EavDataAttributeGroupInterface"
     */
    public function testEavDataAttributeGroupInterface()
    {
    }

    /**
     * Test attribute "attribute_group_id"
     */
    public function testPropertyAttributeGroupId()
    {
    }

    /**
     * Test attribute "attribute_group_name"
     */
    public function testPropertyAttributeGroupName()
    {
    }

    /**
     * Test attribute "attribute_set_id"
     */
    public function testPropertyAttributeSetId()
    {
    }

    /**
     * Test attribute "extension_attributes"
     */
    public function testPropertyExtensionAttributes()
    {
    }
}
