<?php
/**
 * CatalogProductAttributeMediaGalleryManagementV1ApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Magento2Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Magento Enterprise
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Magento2Client;

use \Swagger\Magento2Client\Configuration;
use \Swagger\Magento2Client\ApiClient;
use \Swagger\Magento2Client\ApiException;
use \Swagger\Magento2Client\ObjectSerializer;

/**
 * CatalogProductAttributeMediaGalleryManagementV1ApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Magento2Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CatalogProductAttributeMediaGalleryManagementV1ApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for catalogProductAttributeMediaGalleryManagementV1CreatePost
     *
     * .
     *
     */
    public function testCatalogProductAttributeMediaGalleryManagementV1CreatePost()
    {
    }

    /**
     * Test case for catalogProductAttributeMediaGalleryManagementV1GetGet
     *
     * .
     *
     */
    public function testCatalogProductAttributeMediaGalleryManagementV1GetGet()
    {
    }

    /**
     * Test case for catalogProductAttributeMediaGalleryManagementV1GetListGet
     *
     * .
     *
     */
    public function testCatalogProductAttributeMediaGalleryManagementV1GetListGet()
    {
    }

    /**
     * Test case for catalogProductAttributeMediaGalleryManagementV1RemoveDelete
     *
     * .
     *
     */
    public function testCatalogProductAttributeMediaGalleryManagementV1RemoveDelete()
    {
    }

    /**
     * Test case for catalogProductAttributeMediaGalleryManagementV1UpdatePut
     *
     * .
     *
     */
    public function testCatalogProductAttributeMediaGalleryManagementV1UpdatePut()
    {
    }
}
